describe ("Bug 14618", function(){
    it ("Confirmação bug",function(){
        cy.visit (Cypress.env('empresa'))
        cy.get ("input[placeholder='E-mail ou CNPJ']").type (Cypress.env('loginempresa'))
        cy.get ("input[placeholder='Senha']") .type (Cypress.env('senhaempresa'))
        cy.get (".btn").first().click()
        cy.wait (2000)
        cy.get("li[ui-sref='empresa.cadastro']").click()
        cy.wait (4000)
        cy.get (".bloco-cadastro:nth-child(3) .fa-plus-square").last().click()
        cy.get(".modal-footer > .btn-success").click()
        cy.wait (2000)
        cy.screenshot()
    })
})