describe ("Bug#14622", function(){
    it ("Confirmação de bugs", function(){
        cy.visit ("https://empregabilidade-ui.cronapp.io/#/empresas")
        cy.get ("input[placeholder='E-mail ou CNPJ']").type ("21333333444422")
        cy.get ("input[placeholder='Senha']") .type ("21333")
        cy.get (".btn").first().click()
        cy.wait (2000)
        cy.visit ("https://empregabilidade-ui.cronapp.io/#/empresas/cadastro")
        cy.wait (4000)
        //cadastrando 2 empresas relacionadas
        cy.get("body.pace-done:nth-child(2) div.fill.ng-scope:nth-child(2) div.ng-scope div.container-fluid.bg-branco:nth-child(4) div.container:nth-child(1) div.row div.col-md-12.col-lg-9.main-content.content.ng-scope div.ng-scope:nth-child(1) form.ng-valid-email.ng-valid-pattern.ng-valid-maxlength.ng-valid.ng-valid-required.ng-dirty.ng-valid-mask.ng-valid-parse div.col-lg-12.col-md-12 div.cadastro-tab-content.dados-profissionais.info-cad div.bloco-cadastro:nth-child(3) div.row:nth-child(3) div.bloco-cadastro:nth-child(2) h3:nth-child(1) > i.fas.fa-plus-square").click()
        cy.get("input[name='razaoSocialER']").type("Cypress")
        cy.get("input[name='nomeFantasiaER']").type("Cypress")
        cy.get("input[name='cnpjER']").type("28309496000107")
        cy.get ("select[id=paisSelecionadoER]").select("BRASIL")
        cy.get ("input[name=cepER]").type("01001000")
        cy.get("input[name=enderecoER]").type("Praça da Sé")
        cy.get("input[id=numeroER]").type("666")
        cy.get("select[id=municipioER]").select("Adolfo")
        cy.get(".bloco-cadastro:nth-child(4) .fas").click()
        cy.get("tr.ng-scope > td:nth-child(2) > input").type("Jonas themonio")
        cy.get("tr.ng-scope > td:nth-child(3) > input").type("71999999999")
        cy.get("tr.ng-scope > td:nth-child(4) > input").type("email@email.io")
        cy.get(".modal-footer > .btn-success").click()
        cy.wait(2000)
        cy.get("body.pace-done:nth-child(2) div.fill.ng-scope:nth-child(2) div.ng-scope div.container-fluid.bg-branco:nth-child(4) div.container:nth-child(1) div.row div.col-md-12.col-lg-9.main-content.content.ng-scope div.ng-scope:nth-child(1) form.ng-valid-email.ng-valid-pattern.ng-valid-maxlength.ng-valid.ng-valid-required.ng-dirty.ng-valid-mask.ng-valid-parse div.col-lg-12.col-md-12 div.cadastro-tab-content.dados-profissionais.info-cad div.bloco-cadastro:nth-child(3) div.row:nth-child(3) div.bloco-cadastro:nth-child(2) h3:nth-child(1) > i.fas.fa-plus-square").click()
        cy.get("body.pace-done.modal-open:nth-child(2) div.fill.ng-scope:nth-child(2) div.ng-scope div.container-fluid.bg-branco:nth-child(4) div.container:nth-child(1) div.row div.col-md-12.col-lg-9.main-content.content.ng-scope div.modal.fade.ng-scope.in:nth-child(4) form.ng-dirty.ng-valid-maxlength.ng-valid-parse.ng-valid-mask.ng-invalid.ng-invalid-required div.modal-dialog.modal-lg div.modal-content div.modal-header > button.close").click()
        cy.get("body.pace-done:nth-child(2) div.fill.ng-scope:nth-child(2) div.ng-scope div.container-fluid.bg-branco:nth-child(4) div.container:nth-child(1) div.row div.col-md-12.col-lg-9.main-content.content.ng-scope div.ng-scope:nth-child(1) form.ng-valid-email.ng-valid-pattern.ng-valid-maxlength.ng-valid.ng-valid-required.ng-dirty.ng-valid-mask.ng-valid-parse div.col-lg-12.col-md-12 div.cadastro-tab-content.dados-profissionais.info-cad div.bloco-cadastro:nth-child(3) div.row:nth-child(3) div.bloco-cadastro:nth-child(2) h3:nth-child(1) > i.fas.fa-plus-square").click()
        cy.get("input[name='razaoSocialER']").type("Cypress2.0")
        cy.get("input[name='nomeFantasiaER']").type("Cypress filial2")
        cy.get("input[name='cnpjER']").type("83509364000129")
        cy.get ("select[id=paisSelecionadoER]").select("BRASIL")
        cy.get ("input[name=cepER]").type("01001000")
        cy.get("input[name=enderecoER]").type("Praça da Sé")
        cy.get("input[id=numeroER]").type("666")
        cy.get("select[id=municipioER]").select("Adolfo")
        cy.get(".bloco-cadastro:nth-child(4) .fas").click()
        cy.get("tr.ng-scope > td:nth-child(2) > input").type("Jonas themonio")
        cy.get("tr.ng-scope > td:nth-child(3) > input").type("71999999999")
        cy.get("tr.ng-scope > td:nth-child(4) > input").type("email@email.io")
        cy.wait(3000)
        cy.get(".modal-footer > .btn-success").click()
        cy.wait(3000)
        cy.reload()
        
    })
})
