describe ("Bug 14618", function(){
    it ("Empresa relacionada",function(){
        cy.visit (Cypress.env('empresa'))
        cy.get ("input[placeholder='E-mail ou CNPJ']").type (Cypress.env('loginempresa'))
        cy.get ("input[placeholder='Senha']") .type (Cypress.env('senhaempresa'))
        cy.get (".btn").first().click()
        cy.wait (2000)
        cy.get("li[ui-sref='empresa.cadastro']").click()
        cy.wait (4000)
        cy.get (".bloco-cadastro:nth-child(3) .fa-plus-square").last().click()
        cy.get("input[name='razaoSocialER']").type("Cronapp")
        cy.get("input[name='nomeFantasiaER']").type("Cronapp")
        cy.get("input[name='cnpjER']").type("08813341000198")
        cy.get ("div.row > div:nth-child(1) > div:nth-child(5) > input").type("cronapp.io")
        cy.get ("select[id=paisSelecionadoER]").select("BRASIL")
        cy.get ("input[name=cepER]").type("01001000")
        cy.get("input[name=enderecoER]").type("Praça da Sé")
        cy.get("input[id=numeroER]").type("666")
        cy.get("select[id=municipioER]").select("Adolfo")
        cy.get(".bloco-cadastro:nth-child(4) .fas").click()
        cy.get("tr.ng-scope > td:nth-child(2) > input").type("Jonas themonio")
        cy.get("tr.ng-scope > td:nth-child(3) > input").type("71999999999")
        cy.get("tr.ng-scope > td:nth-child(4) > input").type("email@email.io")
        cy.get(".modal-footer > .btn-success").click()
        cy.wait (3000)
        cy.get(".btn-controllers-align:nth-child(7) > .btn-edit > .fas").last().click()
        cy.screenshot()
    })
})